### ISSUE TITLE
Using different language

### ISSUE THREAD

**Issue by pltrdy** [bayomim/OntoSeg#1]
Hi @bayomim, thanks for opening this code! 

I'm wondering how could I this on another language, (French in my case)?
I'm not familiar with DBpedia and thus, I'm not sure if/how it's possible.

Thanks.

**Comment by bayomim** [comment]
Hi @pltrdy 
To use OntoSeg with other languages (e.g. French),  you need first to convert your text into vectors of classes from DBpedia. 

This requires the use of [BuildVSM](https://github.com/bayomim/BuildVSM)

In BuildVSM, in the [dbp_annotate](https://github.com/bayomim/BuildVSM/tree/master/node_modules/dbp_annotate) module, change:
` mlspotlight.fixToEndpoint('english'); ` to ` mlspotlight.fixToEndpoint('french'); `

This will change the default language of [DBpediaSpotlight]( https://github.com/dbpedia-spotlight/DBpediaSpotlight.js) 

In BuildVSM in the [convertToVSM.js](https://github.com/bayomim/BuildVSM/blob/master/convertToVSM.js) file, add your folder where your text files are:
`walk("path/to/textFiles/directory",function (err, outResults) { ....`

It will convert it into classes from DBpedia and write the new output in the same folder with new file that is named as the text file with `_vsm` added to it. Example: `filename.txt` to `filename_vsm.txt`

Then you can feed these files to OntoSeg.

**Comment by pltrdy** [comment]
Thanks for this detailed and fast answer :)
